name: 'dbt_project_profile'
version: '1.0.0'
config-version: 2

profile: 'dbt_project_profile'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets:
  - "target"

models:
  dbt_project_profile:
    staging:
      +materialized: view
    marts:
      +materialized: table