version: 2

sources:
  - name: lab10_raw
    database: curso-gcp-bigquery-504610
    tables:
      - name: raw_orders

models:
  - name: stg_raw_orders
    description: "Capa staging: Limpieza y casteo de tipos de la tabla raw_orders."
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: fct_orders_summary
    description: "Capa Marts: Resumen analítico consolidado por cliente."